import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import UtmCapture from "@/components/UtmCapture";

// Single site-wide font. Poppins isn't a variable font on Google Fonts, so
// (unlike the previous Fraunces/Inter setup) the weights actually used
// across the site have to be listed explicitly — 400/500/600 covers every
// font-normal/font-medium/font-semibold in the codebase today. Add a weight
// here if a future component needs one (e.g. "700" for font-bold).
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
  display: "swap",
});

const siteUrl = "https://www.yourdayhouse.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "The Day House | Adult Day Program for Dementia in the Treasure Valley",
    template: "%s | The Day House",
  },
  description:
    "The Day House is a new daytime community coming soon to the Treasure Valley for adults living with memory loss and dementia. Join our interest list for opening updates and enrollment information.",
  openGraph: {
    // Image is generated by app/opengraph-image.tsx using the real brand
    // mark; consider a fuller designed image with real photography once
    // that's available.
    title: "The Day House | Adult Day Program for Dementia in the Treasure Valley",
    description:
      "The Day House is a new daytime community coming soon to the Treasure Valley for adults living with memory loss and dementia. Join our interest list for opening updates and enrollment information.",
    url: siteUrl,
    siteName: "The Day House",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Day House | Adult Day Program for Dementia in the Treasure Valley",
    description:
      "A new daytime community coming soon to the Treasure Valley for adults living with memory loss and dementia.",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="flex min-h-screen flex-col">
        <UtmCapture />
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-full focus:bg-ink focus:px-5 focus:py-3 focus:text-cream"
        >
          Skip to main content
        </a>
        <Nav />
        <main id="main-content" className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
